### ISSUE TITLE
guard validate.sh script fails with an error

### ISSUE THREAD

**Issue by sahroshan** [kubevious/kubevious#76]
### Describe the bug
when running guard validate script I am getting below error.

```
cat deployment.yaml | sh <(curl -sfL https://run.kubevious.io/validate.sh)
/dev/fd/63: 2: Bad substitution
/dev/fd/63: 2: Bad substitution

**** KUBEVIOUS CHANGE VALIDATOR ****

/dev/fd/63: 121: Syntax error: "(" unexpected (expecting "}")
```

### To Reproduce
1. On a fresh ec2 ubuntu 20.04 machine
2. copy  deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  namespace: roshan
spec:
  selector:
    matchLabels:
      app: kuard
      env: prod
  replicas: 1
  revisionHistoryLimit: 10
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: kuard
        env: prod
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:green
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 8080
              path: /ready
            initialDelaySeconds: 2
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
```

3. run command `cat deployment.yaml | sh <(curl -sfL https://run.kubevious.io/validate.sh)`

### Expected behavior
validate script should show issues with the yaml.

### Environment Details:
 - Kubernetes Distribution/Version [minikube]
 - Browser [chrome]
 - Version [1.0.10]

### Additional context
I tried changing sh to bash. But then I run into another issue as below.
```
cat deployment.yaml | bash <(curl -sfL https://run.kubevious.io/validate.sh)

**** KUBEVIOUS CHANGE VALIDATOR ****

👉 *** Reading Input...
✅     Reading Input. Done.
👉 *** Parsing Input...
Input Length: 1578
✅     Parsing Input. Done.
👉 *** Building Package...
✅     Building Package. Done.
👉 *** Apply Package...
error: error parsing STDIN: error converting YAML to JSON: yaml: line 10: could not find expected ':'
🔴🔴🔴
🔴🔴🔴 ERROR: Could not apply change request. Make sure you have write access to kubevious.io/v1 ChangePackage
🔴🔴🔴
```
